//
// Win32\ReleaseAVX\framebuffer_rgba8_ispc_sse2.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_WIN32_RELEASEAVX_FRAMEBUFFER_RGBA8_ISPC_SSE2_H
#define ISPC_WIN32_RELEASEAVX_FRAMEBUFFER_RGBA8_ISPC_SSE2_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_WIN32_RELEASEAVX_FRAMEBUFFER_RGBA8_ISPC_SSE2_H
