//
// Win32\ReleaseAVX\framebuffer_rgb8_ispc_sse4.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_WIN32_RELEASEAVX_FRAMEBUFFER_RGB8_ISPC_SSE4_H
#define ISPC_WIN32_RELEASEAVX_FRAMEBUFFER_RGB8_ISPC_SSE4_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_WIN32_RELEASEAVX_FRAMEBUFFER_RGB8_ISPC_SSE4_H
