//
// Win32\ReleaseAVX\image3c_ispc_sse4.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_WIN32_RELEASEAVX_IMAGE3C_ISPC_SSE4_H
#define ISPC_WIN32_RELEASEAVX_IMAGE3C_ISPC_SSE4_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus
#ifndef __ISPC_STRUCT_vec3uc__
#define __ISPC_STRUCT_vec3uc__
struct vec3uc {
    uint8_t x;
    uint8_t y;
    uint8_t z;
};
#endif


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void *  Image3c__new(const int32_t size_x, const int32_t size_y, struct vec3uc * data, const bool copy);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_WIN32_RELEASEAVX_IMAGE3C_ISPC_SSE4_H
