//
// Win32\ReleaseAVX\material_ispc_avx.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_WIN32_RELEASEAVX_MATERIAL_ISPC_AVX_H
#define ISPC_WIN32_RELEASEAVX_MATERIAL_ISPC_AVX_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_WIN32_RELEASEAVX_MATERIAL_ISPC_AVX_H
