//
// Win32\ReleaseAVX\swapchain_ispc_sse4.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_WIN32_RELEASEAVX_SWAPCHAIN_ISPC_SSE4_H
#define ISPC_WIN32_RELEASEAVX_SWAPCHAIN_ISPC_SSE4_H

#include <stdint.h>



#ifdef __cplusplus
namespace ispc { /* namespace */
#endif // __cplusplus

///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
extern "C" {
#endif // __cplusplus
    extern void *  SwapChainRGB8__new(const uint32_t width, const uint32_t height, const uint32_t depth, void *  * ptrs);
    extern void *  SwapChainRGBA8__new(const uint32_t width, const uint32_t height, const uint32_t depth, void *  * ptrs);
    extern void *  SwapChainRGBFloat32__new(const uint32_t width, const uint32_t height, const uint32_t depth, void *  * ptrs);
    extern void *  SwapChain__map(void * _this, int32_t id);
    extern void SwapChain__swap(void * _this);
    extern void SwapChain__unmap(void * _this);
#if defined(__cplusplus) && !defined(__ISPC_NO_EXTERN_C)
} /* end extern C */
#endif // __cplusplus


#ifdef __cplusplus
} /* namespace */
#endif // __cplusplus

#endif // ISPC_WIN32_RELEASEAVX_SWAPCHAIN_ISPC_SSE4_H
